"""Init

Revision ID: c5466e4a3bbb
Revises: 
Create Date: 2022-12-12 17:18:05.410276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5466e4a3bbb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('editions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titles_of_the_publication', sa.String(), nullable=False),
    sa.Column('index_of_the_publication', sa.Integer(), nullable=True),
    sa.Column('type_of_publication', sa.String(), nullable=True),
    sa.Column('the_cost_of_searches_in_months', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_editions_id'), 'editions', ['id'], unique=False)
    op.create_index(op.f('ix_editions_index_of_the_publication'), 'editions', ['index_of_the_publication'], unique=True)
    op.create_index(op.f('ix_editions_the_cost_of_searches_in_months'), 'editions', ['the_cost_of_searches_in_months'], unique=False)
    op.create_index(op.f('ix_editions_titles_of_the_publication'), 'editions', ['titles_of_the_publication'], unique=False)
    op.create_index(op.f('ix_editions_type_of_publication'), 'editions', ['type_of_publication'], unique=False)
    op.create_table('recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('patronymic', sa.String(), nullable=True),
    sa.Column('recipient_code', sa.Integer(), nullable=True),
    sa.Column('outside', sa.String(), nullable=False),
    sa.Column('house_number', sa.String(), nullable=False),
    sa.Column('apartment_number', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipients_apartment_number'), 'recipients', ['apartment_number'], unique=False)
    op.create_index(op.f('ix_recipients_house_number'), 'recipients', ['house_number'], unique=False)
    op.create_index(op.f('ix_recipients_id'), 'recipients', ['id'], unique=False)
    op.create_index(op.f('ix_recipients_name'), 'recipients', ['name'], unique=False)
    op.create_index(op.f('ix_recipients_outside'), 'recipients', ['outside'], unique=False)
    op.create_index(op.f('ix_recipients_patronymic'), 'recipients', ['patronymic'], unique=False)
    op.create_index(op.f('ix_recipients_recipient_code'), 'recipients', ['recipient_code'], unique=True)
    op.create_index(op.f('ix_recipients_surname'), 'recipients', ['surname'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_period', sa.Integer(), nullable=False),
    sa.Column('month_of_delivery_start', sa.Integer(), nullable=False),
    sa.Column('year_of_delivery_start', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('edition_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['edition_id'], ['editions.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_month_of_delivery_start'), 'subscriptions', ['month_of_delivery_start'], unique=False)
    op.create_index(op.f('ix_subscriptions_subscription_period'), 'subscriptions', ['subscription_period'], unique=False)
    op.create_index(op.f('ix_subscriptions_year_of_delivery_start'), 'subscriptions', ['year_of_delivery_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_year_of_delivery_start'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_subscription_period'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_month_of_delivery_start'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_recipients_surname'), table_name='recipients')
    op.drop_index(op.f('ix_recipients_recipient_code'), table_name='recipients')
    op.drop_index(op.f('ix_recipients_patronymic'), table_name='recipients')
    op.drop_index(op.f('ix_recipients_outside'), table_name='recipients')
    op.drop_index(op.f('ix_recipients_name'), table_name='recipients')
    op.drop_index(op.f('ix_recipients_id'), table_name='recipients')
    op.drop_index(op.f('ix_recipients_house_number'), table_name='recipients')
    op.drop_index(op.f('ix_recipients_apartment_number'), table_name='recipients')
    op.drop_table('recipients')
    op.drop_index(op.f('ix_editions_type_of_publication'), table_name='editions')
    op.drop_index(op.f('ix_editions_titles_of_the_publication'), table_name='editions')
    op.drop_index(op.f('ix_editions_the_cost_of_searches_in_months'), table_name='editions')
    op.drop_index(op.f('ix_editions_index_of_the_publication'), table_name='editions')
    op.drop_index(op.f('ix_editions_id'), table_name='editions')
    op.drop_table('editions')
    # ### end Alembic commands ###
